#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - box

before_script:
  - npm install
  - npm install -g firebase-tools
#  - npm install -g polymer-cli

script:
#  - polymer build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  
